import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import EditItemForm from '../components/EditItemForm'
import AddItemForm from '../components/AddItemForm'
import { useState } from 'react'
import ShoppingList from '../components/ShoppingList'
import { QueryClient, QueryClientProvider } from 'react-query'

const inter = Inter({ subsets: ['latin'] })

const queryClient = new QueryClient();

export default function Home() {
  const [editingIndex, setEditingIndex] = useState<any>(null);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QueryClientProvider client={queryClient}>
      <main className="container">
          <div className="content">
            <h1 id="main-title">Shopping List</h1>
            <div className="flex-row">
              <div className="flex-large one-fourths side-menu">
              {editingIndex !== null ? (
              <>
                <EditItemForm
                  editingIndex={editingIndex}
                  setEditingIndex={setEditingIndex}
                />
              </>
            ) : (
              <AddItemForm />
            )}
              </div>
              <div className="flex-small three-fourths">
                <ShoppingList setEditingIndex={setEditingIndex} />
              </div>
            </div>
          </div>
      </main>
      </QueryClientProvider>
    </>
  )
}
